In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [26]:
data = pd.read_csv("../Data/churn.csv")

In [27]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [28]:
data.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [29]:
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")
data["TotalCharges"] = data["TotalCharges"].fillna(0)

In [30]:
data["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [31]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2279.734304
std         0.368612    24.559481       30.090047   2266.794470
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000     9.000000       35.500000    398.550000
50%         0.000000    29.000000       70.350000   1394.550000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000

In [32]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [33]:
data = data.drop("customerID",axis = 1)

In [34]:
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [35]:
X = data.drop("Churn",axis = 1)
Y = data["Churn"]

# handle categorical value

In [36]:
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder

In [37]:
label_encoder = LabelEncoder()
OneHot_Encoder = OneHotEncoder()

In [38]:
label_columns = ["gender","Partner","Dependents","PhoneService","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies","PaperlessBilling"]
onehot_columns = ["MultipleLines","InternetService","Contract","PaymentMethod"]

In [39]:
for col in X[label_columns]:
    X[col] = label_encoder.fit_transform(X[col])

In [40]:
for col in onehot_columns:
    encoder = OneHotEncoder(sparse_output=False)
    onehot_encoded = encoder.fit_transform(X[[col]])
    encoded_df = pd.DataFrame(
        onehot_encoded,
        columns=[f"{col}_{cat}" for cat in encoder.categories_[0]],
        index=X.index
    )
    X = pd.concat([X, encoded_df], axis=1)
    if col in X.columns:
        X.drop(columns=[col], inplace=True)

In [41]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
       'MonthlyCharges', 'TotalCharges', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [42]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7043 non-null   int64
 1   SeniorCitizen                            7043 non-null   int64
 2   Partner                                  7043 non-null   int64
 3   Dependents                               7043 non-null   int64
 4   tenure                                   7043 non-null   int64
 5   PhoneService                             7043 non-null   int64
 6   OnlineSecurity                           7043 non-null   int64
 7   OnlineBackup                             7043 non-null   int64
 8   DeviceProtection                         7043 non-null   int64
 9   TechSupport                              7043 non-null   int64
 10  StreamingTV                              7043 non-null   int64
 11  StreamingMovies                          7043 non-null   int64
 12  PaperlessBilling                         7043 non-null   int64
 13  MonthlyCharges                           7043 non-null   float64
 14  TotalCharges                             7043 non-null   float64
 15  MultipleLines_No                         7043 non-null   float64
 16  MultipleLines_No phone service           7043 non-null   float64
 17  MultipleLines_Yes                        7043 non-null   float64
 18  InternetService_DSL                      7043 non-null   float64
 19  InternetService_Fiber optic              7043 non-null   float64
 20  InternetService_No                       7043 non-null   float64
 21  Contract_Month-to-month                  7043 non-null   float64
 22  Contract_One year                        7043 non-null   float64
 23  Contract_Two year                        7043 non-null   float64
 24  PaymentMethod_Bank transfer (automatic)  7043 non-null   float64
 25  PaymentMethod_Credit card (automatic)    7043 non-null   float64
 26  PaymentMethod_Electronic check           7043 non-null   float64
 27  PaymentMethod_Mailed check               7043 non-null   float64
dtypes: float64(15), int64(13)
memory usage: 1.5 MB

In [43]:
X.shape

(7043, 28)

# split the data into training and test data

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split (
    X,
    Y,
    random_state = 42,
    test_size = 0.2
)

# handle numerical columns

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
scaler = StandardScaler()

In [48]:
numeric_cols = ["tenure", "MonthlyCharges", "TotalCharges"]

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

# model training

In [49]:
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier

In [50]:
linear_model = LogisticRegression()
tree_model = DecisionTreeClassifier()
forest_model = RandomForestClassifier()

In [51]:
TREE_MODEL = tree_model.fit(X_train_scaled, y_train)
FOREST_MODEL = forest_model.fit(X_train_scaled, y_train)
LINEAR_MODEL = linear_model.fit(X_train_scaled, y_train)

In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [53]:
tree_accuracy = accuracy_score(y_test, TREE_MODEL.predict(X_test_scaled))
forest_accuracy = accuracy_score(y_test, FOREST_MODEL.predict(X_test_scaled))
linear_accuracy = accuracy_score(y_test, LINEAR_MODEL.predict(X_test_scaled))

In [54]:
print("Decision Tree Accuracy:", tree_accuracy)
print("Random Forest Accuracy:", forest_accuracy)
print("Logistic Regression Accuracy:", linear_accuracy)

Decision Tree Accuracy: 0.7182398864442867
Random Forest Accuracy: 0.7920511000709723
Logistic Regression Accuracy: 0.8211497515968772